excluded:
    - Pods
disabled_rules:
    - force_try
    - for_where
    - force_cast
    - block_based_kvo
    - identifier_name
    - trailing_whitespace
    - switch_case_alignment
    - function_parameter_count
    - void_function_in_ternary
force_try: warning
force_cast: warning
cyclomatic_complexity: 20
line_length:
    warning: 280
    error: 360
    ignores_function_declarations: true
    ignores_comments: true
file_length:
    warning: 1000
    error: 1500
function_body_length:
    warning: 120
    error: 150
type_body_length:
    warning: 800
    error: 1200
switch_case_alignment: false
